config/routes.rb
Factory::Application.routes.draw do

  resources :roles

  get "pages/about", :as => "about"
  
  match 'people/unanswered', :as => :unanswered
  match 'stypes/switcher' => 'stypes#switcher'
  match 'users/:id/people' => 'users#own_people', :as => :user_people
  match 'people/rss', :as => :rss
  match 'photos/:id/delete' => 'photos#delete', :as => :delete_photo

  devise_for :users
  resources :users

  resources :people do  
    resources :answers
  end 

  resources :stypes
  
  

  root :to => "people#index"

end

app/models/person.rb
# == Schema Information
# Schema version: 20101104173614
#
# Table name: people
#
#  id         :integer         not null, primary key
#  content    :text
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#  gender     :string(255)
#

class Person < ActiveRecord::Base

  has_many :answers, :dependent => :destroy, :inverse_of => :person
  has_many :photos, :dependent => :destroy
  has_many :videos, :dependent => :destroy
  belongs_to :user, :inverse_of => :people

  accepts_nested_attributes_for :photos, :reject_if => proc { |a| a.all? { |k, v| v.blank? }}
  accepts_nested_attributes_for :videos, :reject_if => lambda { |a| a[:video_code].blank? }, :allow_destroy => true
  
  validates :title,   :presence => true, :length => { :maximum => 140 }
  validates :content, :presence => true
  validates :gender, :presence => true

  default_scope :order => 'people.created_at DESC'

  attr_accessible :content, :title, :answers_attributes, :gender, :photos_attributes, :videos_attributes
  GENDERS = {'male' => 'Мужчина', 'female' => 'Женщина'}
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_filter :authenticate_user!, :except => :rss
  load_and_authorize_resource :except => [:unanswered, :rss]
  def rss
    @people = Person.all
    respond_to do |format|
      format.atom 
    end
  end

  def index
    @stypes = Stype.find(:all)
    @people = params[:user_id].nil? ? Person.all(:include => [:user, :answers]) : User.find_by_id(params[:user_id]).people
    respond_to do |format|
      format.json { render :json => @people }
      format.xml  { render :xml => @people }
      format.atom 
      format.html
    end
    #@people = Person.all(:include => [:user, :answers])
  end

  def show
    @stypes = Stype.find(:all)
  end

  def new
    
  end

  def edit
    
  end

  def create
    @person.user = current_user
    if @person.save
      flash[:success] = 'Ок, пусть теперь отвечают.'
      redirect_to people_path
    else
      render :new
    end
      
  end

  def update
    if @person.update_attributes(params[:person])
      flash[:success] = 'Ок, пусть теперь отвечают.'
      redirect_to people_path
    else
      render :index
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

  def unanswered
    @people = Person.all - current_user.answered_people
    @stypes = Stype.all
    authorize! :read, Person
    render :index
  end


end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for person, :html => { :multipart => true }  do |f| %>

  <%= render 'shared/error_messages', :object => f.object %>

  <% unless person.new_record? %>
    <% for photo in person.photos %>
      <span id="photo_<%= photo.id %>" class="photo_holder">
        <%= image_tag(photo.data(:thumb)) %>
        <span class="delete_photo"><%= link_to "delete", delete_photo_path(photo.id), :remote => true %></span>
      </span>
    <% end %>
  <% end %>
  <div id=video_form">
  <% f.fields_for :videos do |builder| %>
    <%= render 'video_fields', :f => builder %>
  <% end %>  
  </div>
  <p><%= link_to_add_fields "Добавить фото", f, :photos %> или <%= link_to_add_fields "Youtube видео", f, :videos, true %></p>

  
  <div class="field">
    <%= f.label :title, "Имя", :class => 'text_field_label' %><br />
    <%= f.text_field :title, :class => 'text_field big wide' %>
  </div>

  <div class="field" style="padding-top:15px;">
    <%= f.label :content, "Описание", :class => 'text_field_label'  %><br />
    <%= f.text_area :content, :escape => false, :class => 'wide' %>
  </div>
  <div>
    <% Person::GENDERS.each do |gender, translated|  %>
      <%= f.radio_button :gender, gender %>
      <%= f.label :gender, translated, :value => gender %>
    <% end %>
  </div>
  <div class="actions" style="padding-top:15px; padding-bottom:15px;">
    <%= f.submit "Отправить", :class => 'big_button'%>
  </div>

<% end %>

app/views/people/_person.html.erb
<div class="contentbox person" id="person_<%= person.id %>">

  <div class="post_header"><h2><%= link_to_unless_current person.title, person %><span class='author'>by <%= person.user.login %></span></h2></div>
  
  <% if person.photos.any? %>
    <%= image_tag(person.photos.first.data.url) %>
    <% person.photos.shift %>
  <% elsif person.videos.any? %>
      <object width="590" height="467">
          <param name="movie" value="http://www.youtube.com/v/<%= person.videos.first.video_id %>&hl=en"></param>
          <param name="wmode" value="transparent"></param>
          <embed src="http://www.youtube.com/v/<%= person.videos.first.video_id %>&hl=en" type="application/x-shockwave-flash" wmode="transparent" width="590" height="467"></embed>
      </object>
      <% person.videos.shift %>
  <% end %>
  
    <% for photo in person.photos %>
      <div class="thumbnail" id="tinyboxphoto<%= photo.id %>"><%= image_tag(photo.data(:thumb)) %></div>
    <% end %>
  
    <% for video in person.videos %>
      <div class="thumbnail" id="tinyboxvideo<%= video.id %>"><%= image_tag "http://img.youtube.com/vi/" + video.video_id + "/default.jpg" %></div>
    <% end %>
  
  <div class="post_content readable clear">
    <%= raw person.content %>
  </div>

  <% if can? :update, person -%>
    <div class="misc">
      <span class="destroy">
        <%= link_to "edit", edit_person_path(person) %>
        <% if can? :delete, person %><%= link_to "delete", person, :method => :delete,
                                      :confirm => "You sure?",
                                      :title => person.title %><% end %>
      </span>
    </div>
  <% end -%>

  <div class="answers" id="answers_<%= person.id %>">
    <% unless person.answers.empty? -%>
      <%= render :partial => 'answers/answer', :collection => person.answers %>
    <% end -%>
  </div>
</div>
<% if can? :create, Answer -%>
  <% unless person.answers.any? { |answer| answer.user.id == current_user.id } -%>
    <%= render :partial => 'answers/answer_form', :locals => { :person => person, :answer => Answer.new } %>
  <% end -%>
<% end -%>

<script type="text/javascript">
  <% for photo in person.photos %>
      var contentphoto<%= photo.id %> = '<%= image_tag(photo.data.url, :size => photo.geometry) %>';
      T$('tinyboxphoto<%= photo.id %>').onclick = function(){TINY.box.show(contentphoto<%= photo.id %>,0,0,0,1)}
  <% end %>
  <% for video in person.videos %>
      var contentvideo<%= video.id %> = '<object width="590" height="467"><param name="movie" value="http://www.youtube.com/v/<%= video.video_id %>&hl=en"></param><param name="wmode" value="transparent"></param><embed src="http://www.youtube.com/v/<%= video.video_id %>&hl=en" type="application/x-shockwave-flash" wmode="transparent" width="590" height="467"></embed></object>';
      T$('tinyboxvideo<%= video.id %>').onclick = function(){TINY.box.show(contentvideo<%= video.id %>,0,590,467,1)}
  <% end %>
</script>

app/views/people/_photo_fields.html.erb
<div class='photo fields'>
  <%= f.file_field :data %>
  <div id="photo_format_tooltip">JPEG, GIF, PNG or BMP.&nbsp;&nbsp; <b>Max size: 3 MB</b></div>
  <%= link_to_remove_fields "Отмена", f %>
</div>

app/views/people/_video_fields.html.erb
<div class='video fields'>
  <%= f.label :video_code, "Embed code or URL (YouTube only!)", :class=> 'video_label' %><br />
  <%= f.text_area :video_code, :class=> "not_so_wide" %><br />
  <%= link_to_remove_fields "Удалить", f  %>
</div>

app/views/people/edit.html.erb
<% title "Редактировать #{@person.title}" %>

<div class="contentbox">

<h2>Редактировать</h2>

<%= render 'form', :person => @person %>

<%= link_to 'Back', people_path %>

<div/>

app/views/people/index.html.erb
<% if ((@people.length == 0) and (params[:action] == 'unanswered')) %>
  <% title "Нет никого" %>
  <%= render :partial => 'shared/nothing' %>
<% elsif @people.length == 0 %>
  <% title "Нет никого" %>
  <div class='contentbox'>&laquo;По вашему запросу ничего не найдено&raquo;. <% if can? :create, Person %><%= link_to new_person_path do %>Создайте&nbsp;свой запрос на типирование<% end -%><% end %>.
<% else  %>
  <% title "Все персоны" %>
  <%= render :partial => 'people/person', :collection => @people %>
<% end %>

app/views/people/new.html.erb
<% title "Новый запрос" %>
<div class="contentbox">

<h2>Новый запрос</h2>

<%= render 'form', :person => @person %>

<%= link_to 'Back', people_path %>
</div>

app/views/people/show.html.erb
<% title @person.title %>
<%= render @person %>