config/routes.rb
Factory::Application.routes.draw do

  resources :roles

  get "pages/about", :as => "about"
  
  match 'people/unanswered', :as => :unanswered
  match 'stypes/switcher' => 'stypes#switcher'
  match 'users/:id/people' => 'users#own_people', :as => :user_people
  match 'people/rss', :as => :rss
  match 'photos/:id/delete' => 'photos#delete', :as => :delete_photo

  devise_for :users
  resources :users

  resources :people do  
    resources :answers
  end 

  resources :stypes
  
  

  root :to => "people#index"

end

app/models/user.rb
# == Schema Information
# Schema version: 20101023092807
#
# Table name: users
#
#  id                   :integer         not null, primary key
#  email                :string(255)     default(""), not null
#  encrypted_password   :string(128)     default(""), not null
#  password_salt        :string(255)     default(""), not null
#  reset_password_token :string(255)
#  remember_token       :string(255)
#  remember_created_at  :datetime
#  sign_in_count        :integer         default(0)
#  current_sign_in_at   :datetime
#  last_sign_in_at      :datetime
#  current_sign_in_ip   :string(255)
#  last_sign_in_ip      :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  login                :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  before_create :create_login

  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids, :login
  
  has_many :people, :inverse_of => :user
  has_many :answers, :inverse_of => :user
  has_many :answered_people, :through => :answers, :source => :person, :inverse_of => :user
  has_and_belongs_to_many :roles
  
  
  
  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end
  
  def create_login             
    email = self.email.split(/@/)
    self.login = email[0]
  end
  
  def human_login
    self.login.split('-').join(' ').split('.').join(' ').titleize
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication
 
  def check_permissions
    authorize! :create, resource
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, :only => [:index,:new,:edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  load_and_authorize_resource :only => [:show,:new,:destroy,:edit,:update]
 
  # GET /users
  # GET /users.xml                                                
  # GET /users.json                                       HTML and AJAX
  #-----------------------------------------------------------------------
  def index
    @users = User.accessible_by(current_ability, :index).limit(20)
    respond_to do |format|
      format.json { render :json => @users }
      format.xml  { render :xml => @users }
      format.html
    end
  end
 
  # GET /users/new
  # GET /users/new.xml                                            
  # GET /users/new.json                                    HTML AND AJAX
  #-------------------------------------------------------------------
  def new
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
  end
 
  # GET /users/1
  # GET /users/1.xml                                                       
  # GET /users/1.json                                     HTML AND AJAX
  #-------------------------------------------------------------------
  def show
    @people = @user.answered_people
    @stypes = Stype.find(:all)
    @title = "Ответы"
    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html      
    end
  end
 
  # GET /users/1/edit                                                      
  # GET /users/1/edit.xml                                                      
  # GET /users/1/edit.json                                HTML AND AJAX
  #-------------------------------------------------------------------
  def edit
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
  end
 
  # DELETE /users/1     
  # DELETE /users/1.xml
  # DELETE /users/1.json                                  HTML AND AJAX
  #-------------------------------------------------------------------
  def destroy
    @user.destroy!
 
    respond_to do |format|
      format.json { respond_to_destroy(:ajax) }
      format.xml  { head :ok }
      format.html { respond_to_destroy(:html) }      
    end
  end
 
  # POST /users
  # POST /users.xml         
  # POST /users.json                                      HTML AND AJAX
  #-----------------------------------------------------------------
  def create
    @user = User.new(params[:user])
 
    if @user.save
      respond_to do |format|
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
        format.html { redirect_to :action => :index }
      end
    else
      respond_to do |format|
        format.json { render :text => "Could not create user", :status => :unprocessable_entity } # placeholder
        format.xml  { head :ok }
        format.html { render :action => :new, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  # PUT /users/1.json                                            HTML AND AJAX
  #----------------------------------------------------------------------------
  def update
    if params[:user][:password].blank?
      [:password,:password_confirmation,:current_password].collect{|p| params[:user].delete(p) }
    else
      @user.errors[:base] << "The password you entered is incorrect" unless @user.valid_password?(params[:user][:current_password])
    end
 
    respond_to do |format|
      if @user.errors[:base].empty? and @user.update_attributes(params[:user])
        flash[:notice] = "Your account has been updated"
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
        format.html { redirect_to :action => :index }
      else
        format.json { render :text => "Could not update user", :status => :unprocessable_entity } #placeholder
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        format.html { render :action => :edit, :status => :unprocessable_entity }
      end
    end
  end
  
  def own_people
    @user = User.find(params[:id])
    @stypes = Stype.all
    @people = @user.people
    @title = "Персоны"
    authorize! :read, Person
    render :show
  end
  
  private
  
  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability, :read)
  end
 
  # Make the current user object available to views
  #----------------------------------------
  def get_user
    @current_user = current_user
  end
  
  
  
end

app/views/users/_user_fields.html.erb
<p><%= f.label :email %></p>
<p><%= f.text_field :email %></p>
 
<% if can? :read, Role %>
	<p><%= f.label :role %></p>
	<ul>
		<%= habtm_checkboxes(@user, :role_ids, @accessible_roles, :name) %>
	</ul>
<% end %>

app/views/users/edit.html.erb
<% title "Редактировать #{@user.login}" %>
<div class="contentbox">
<h3><%= @user == @current_user ? "Your Account Settings" : "Edit User" %></h3>
 
<%= form_for(@user, :html => { :method => :put }) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
	<%= render :partial => 'user_fields', :locals => { :f => f } %>
 
	<p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i></p>
	<p><%= f.password_field :password %></p>
 
	<p><%= f.label :password_confirmation %></p>
	<p><%= f.password_field :password_confirmation %></p>
 
	<p><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i></p>
	<p><%= f.password_field :current_password %></p>
 
  <p><%= f.submit "Update" %></p>
<% end %>
<%= link_to "Back", :back %>
</div>

app/views/users/index.html.erb
<% title "Пользователи" %>
<div class="contentbox">
<!-- table header stuff here -->
<table>
<% @users.each do |u| %>
  <tr>
    <td><%= link_to_if(can?(:read, User), "#{u.email}", user_path(u.id)) {} %></td>
    <td><%= "#{u.email}" %></td>
    <td><%= "#{u.roles.collect{|r| r.name}}" %></td>
    <td><%= link_to_if(can?(:edit, User), 'edit', edit_user_path(u.id)) {} %></td>
    <td><%= link_to_if(can?(:delete, u), 'delete', u, :confirm => "Are you sure?", :method => :delete) {} %></td>
  </tr>
<% end %>
</table>
</div>

app/views/users/new.html.erb
<% title "Новый пользователь" %>  
<div class="contentbox">
<h2>Register User</h2>
 
<%= form_for(@user) do |f| %>

  <%= render 'shared/error_messages', :object => f.object %>
 
  <%= render :partial => 'user_fields', :locals => { :f => f } %>
 
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>
 
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
 
  <p><%= f.submit "Register" %></p>
<% end %>
</div>

app/views/users/show.html.erb
<% if params[:action] == "own_people" %>
  <% title @user == current_user ? "Мои персоны" : "Персоны #{@user.login}" %>
<% else %>
  <% title "Ответы #{@user.human_login}" %>
<% end %>
<div class='contentbox'>

  <div class="user-profile">

    <div class="gravatar">
      <%= gravatar_for ( @user, :size => 75 ) %>
    </div>

    <div class="body">
      <div class="stats">
        <div>Created at: <%= @user.created_at %></div>
        <div>Last Sign In: <%= @user.last_sign_in_at %></div>
        <div>Sign In Count: <%= @user.sign_in_count %></div>
      </div>
    
      <h2><%= @user.human_login %>
        <% if can? :manage, @user -%><span class="editlinks">(<%= link_to "Edit", edit_user_path(@user) %> | <%= link_to "Delete", user_path(@user), :confirm => "Are you sure?", :method => :delete %>)</span><% end -%>
      </h2>
    
      <div class="description">
        <% unless @user.roles.empty? -%><%= @user.roles.first.name %><% end -%>
      </div>
    </div>
    <div class="clear"></div>
  </div>
  <h3><%= @title %></h3>
</div>

<% unless @people.empty? %>
  <%= render :partial => 'people/person', :collection => @people %>
<% else %>
  <div class="contentbox readable">
  <% if params[:action] == 'own_people' %>
    <p>Нет никого.</p>
    <% if @user == current_user %><p>Вами пока не создано ни одного запроса. К сожалению.<br><% if can? :create, Person %>Впрочем, <% link_to new_person_path do %>это&nbsp;сделать<% end %> никогда не поздно.<% else %>Впрочем, вы и не можете =)<% end %><% end %>
  <% else %>
    <p>Нет никого.</p>
    <% if @user == current_user %><p>Вы еще никого не протипировали. <% if can? :create, Answer %> <%= link_to 'Можно попробовать', unanswered_path %></p><% end %><% end %>
  <% end %>
  </div>
<% end %>