config/routes.rb
Factory::Application.routes.draw do

  resources :roles

  get "pages/about", :as => "about"
  
  match 'people/unanswered', :as => :unanswered
  match 'stypes/switcher' => 'stypes#switcher'
  match 'users/:id/people' => 'users#own_people', :as => :user_people
  match 'people/rss', :as => :rss
  match 'photos/:id/delete' => 'photos#delete', :as => :delete_photo

  devise_for :users
  resources :users

  resources :people do  
    resources :answers
  end 

  resources :stypes
  
  

  root :to => "people#index"

end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to "На главную", root_path %></li>
      <li><%= link_to "Наши планы", about_path %></li>
    </ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <table id ="sidebar">
    <tr>
      <td>
        <h1><a href="<%= root_path %>">nbspace:<br><span class="marked">Соционика</span></a></h1>
      </td>
      <% if user_signed_in? %>
      <td style="width:25%;">
        <div class="box">
          <div class="box-bar box-people">
            <div class="box-corner"></div>
            <div class="box-bar-text">
              <span class="title"><%= link_to 'Персоны', people_path %></span>
            </div>
          </div>
          <div class="subbar box-people" style="display: none;"></div>

          <div class="box-body">
            <div class="section">
              <ul>
                <li><%= link_to 'Все', people_path %></li>
                <li><%= link_to 'По типу', stypes_path %></li>
              </ul>
            </div>
            <% if can? :create, Person %>
              <div class="footer"><%= link_to 'Создать запрос', new_person_path %> </div>
            <% end %>
          </div>
        </div>
      </td>

      <% if can? :create, Person %>
      <td style="width:25%;">
        <div class="box">
          <div class="box-bar box-user">
            <div class="box-corner"></div>
            <div class="box-bar-text">
              <span class="title"><%= link_to "You", user_path(current_user) %> (<%= link_to "Выйти", destroy_user_session_path -%>)</span>
            </div>
          </div>
          <div class="subbar box-user" style="display: none;"></div>
          <div class="box-body">
            <div class="section">
              <ul>
                <li><%= link_to 'Мои персоны', user_people_path(current_user) %></li>
                <li><%= link_to 'Мои ответы', user_path(current_user) %></li>
                <li><%= link_to 'Отвечать', unanswered_path %></li>
              </ul>
            </div>
          </div>
        </div>
      </td>
      <% end %>


      <td style="width:25%;">
        <div class="box">
          <div class="box-bar box-tim">
            <div class="box-corner"></div>
            <div class="box-bar-text">
              <span class="title"><%= link_to 'Избранные', '#' %></span>
            </div>
          </div>
          <div class="subbar box-tim" style="display: none;"></div>
          <div class="box-body">
            <div class="section">
              Зарезервированно для версии 1.0.0.<br><%= link_to 'Что там будет?', about_path %><!-- <%= form_tag '/stypes/switcher', :method => :get do -%>
					<%= select('stype', 'id', Stype.all.map {|u| [u.title,u.id]})  %><%= submit_tag 'Перейти', :class => 'tim-go' %><% end %> -->
            </div>
          </div>
        </div>
      </td>
      <% end %>



    </tr>
  </table>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %> — nbspace::socionics</title>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
    <link rel="icon" href="/images/favicon.ico" type="image/ico" />
  <link rel="shortcut icon" href="/images/favicon.ico" type="image/ico" />
  
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag :all %>
  <%= auto_discovery_link_tag :atom, rss_path(:format => :atom) %>
  <%= javascript_include_tag 'tinybox' %>

  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  
  <div id="wrapper">
  
    <%= render 'layouts/header' %> 
    <section id='content'>
     <% unless params[:controller] == 'devise/sessions' and params[:action] == 'new' %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
      <% end %>
     <% end %>
      <%= yield %>
    </section>    

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>